app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/urls.py
from os import path
from django.urls import path
from core.views import IndexView, TodosInstrumentosListView, InstrumentoCreateView, EntradasListView, EntradaCreateView, \
                       load_instrumentos, SectorListView, SectorCreateView, RequisicaoListView, RequisicaoCreateView, ResumoListView, \
                       AprovarRequisicao, load_requisicoes, RequisicaoUpdateView
                       

app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('sector/', SectorListView.as_view(), name='sector'),
    path('sector/new', SectorCreateView.as_view(), name='sector-new'),
    path('instrumento/', TodosInstrumentosListView.as_view(), name='instrumento'),
    path('instrumento/new', InstrumentoCreateView.as_view(), name='instrumento-new'),
    path('movimento/', EntradasListView.as_view(), name='entrada'),
    path('movimento/new', EntradaCreateView.as_view(), name='entrada-new'),
    path('movimento/listar-instrumentos', load_instrumentos, name='listar_instrumentos'),
    path('requisicao/', RequisicaoListView.as_view(), name='requisicao'),
    path('requisicao/new', RequisicaoCreateView.as_view(), name='requisicao-new'),
    path('requisicao/edit/<int:pk>/', RequisicaoUpdateView.as_view(), name='requisicao-update'),
    path('resumo/', ResumoListView.as_view(), name='resumo'),
    path('aprovacao/<int:requisicao_id>/requisicao', AprovarRequisicao.as_view(), name='aprovacao'),
    path('aprovacao/requisicao', load_requisicoes, name='aprovacao-requisicao'),
  
]

app/core/models.py
from django.db import models
from user.models import User
from django.db.models.signals import pre_save, post_save



FORNECEDOR = (
    ('ECHO', 'ECHO'),
    ('MISAU', 'MISAU'),
    ('LEVANTAMENTO DEPOSITO', 'LEVANTAMENTO NO DEPOSITO')
)

TIPO_APROVACAO = (
    ('Aprovada', 'Aprovada'),
    ('Rejeitada', 'Rejeitada')
)

STATUS_REQUISICAO = (
    ('Pendente', 'Pendente'),
    ('Aprovada', 'Aprovada'),
    ('Rejeitada', 'Rejeitada'),
)

qs = '"select 1 AS id, p.nome AS provincia, s.nome AS sector, i.nome AS instrumento, i.stock,"\
                                  "i.quantidade_necessaria AS necessidade, i.ano,  e.data_entrada, e.quantidade AS quantidade_entrada, e.fornecedor,"\
                                  "r.id AS requisicao_id, r.data_requisicao, r.quantidade AS quantidade_requisitada, r.status_requisicao from core_instrumento i" \
                                  " inner join core_sector s on s.id=i.sector_id" \
                                  " inner join core_provincia p on i.provincia_id=p.id" \
                                  " left join core_entrada e on e.instrumento_id=i.id" \
                                  " left join core_requisicao r on r.instrumento_id=i.id"'
                                   

class Provincia(models.Model):
    nome = models.CharField(max_length=150)
    
    def __str__(self):
        return self.nome
    
    
class Sector(models.Model):
    nome = models.CharField(max_length=150)
    # provincia = models.ForeignKey(Provincia, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = 'Sector'
        verbose_name_plural = 'Sectores'
    
    def __str__(self):
        return self.nome
    
class Instrumento(models.Model):
    nome = models.CharField(max_length=150)
    stock = models.IntegerField()
    ano = models.PositiveSmallIntegerField()
    quantidade_necessaria = models.IntegerField()
    provincia = models.ForeignKey(Provincia, related_name='instrumentos', on_delete=models.CASCADE)
    sector = models.ForeignKey(Sector, related_name='instrumentos', on_delete=models.CASCADE)
    feito_por = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    feito_em = models.DateTimeField(auto_now=True)
        
    def __str__(self):
        return self.nome
    
class Entrada(models.Model):
    data_entrada = models.DateField()
    fornecedor = models.CharField(max_length=100, choices=FORNECEDOR)
    quantidade = models.IntegerField()
    instrumento = models.ForeignKey(Instrumento, on_delete=models.CASCADE)
    provincia = models.ForeignKey(Provincia, on_delete=models.CASCADE)
    sector = models.ForeignKey(Sector, on_delete=models.CASCADE)
    feito_por = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    feito_em = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.instrumento.nome    

     
class Requisicao(models.Model):
    data_requisicao = models.DateField()
    provincia = models.ForeignKey(Provincia, on_delete=models.CASCADE)
    sector = models.ForeignKey(Sector, on_delete=models.CASCADE)
    instrumento = models.ForeignKey(Instrumento, on_delete=models.CASCADE)
    quantidade = models.IntegerField()
    feito_por = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    feito_em = models.DateTimeField(auto_now=True)
    status_requisicao = models.CharField(max_length=50, choices=STATUS_REQUISICAO, default='Pendente')
    
    class Meta:
        verbose_name = 'Requisicao'
        verbose_name_plural = 'Requisicoes'
        
    def __str__(self):
        return self.instrumento.nome
    
class Aprovacao(models.Model):
    requisicao = models.ForeignKey(Requisicao, on_delete=models.CASCADE)
    tipo_aprovacao = models.CharField(max_length=100, choices=TIPO_APROVACAO)
    comentario = models.TextField(null=True, blank=True)
    feito_por = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    feito_em = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = 'Aprovacao'
        verbose_name_plural = 'Aprovacoes'
        
        
        
class Resumo(models.Model):
    provincia = models.CharField(max_length=100)
    sector = models.CharField(max_length=100)
    instrumento = models.CharField(max_length=100)
    entrada_id = models.IntegerField()
    data_entrada = models.DateField()
    quantidade = models.IntegerField()
    fornecedor = models.CharField(max_length=100)
    stock = models.IntegerField()
    necessidade = models.IntegerField()
    ano = models.PositiveSmallIntegerField()
    id_requisicao = models.IntegerField()
    data_requisicao = models.DateField()
    quantidade_requisicao = models.IntegerField()
    status_requisicao = models.CharField(max_length=100)
    
    class Meta:
        verbose_name = 'Resumo de Instrumento'
        verbose_name_plural = 'Resumo de Instrumentos'
        
    def __str__(self):
        return self.instrumento.nome
    

def update_stock(sender, instance, created, *args, **kwargs):
    if created:
        instrumento = Instrumento.objects.get(entrada=instance)
        instrumento.stock += instance.quantidade
        instrumento.save()
         
post_save.connect(update_stock, sender=Entrada)

def update_requisicao_status(sender, instance, created, *args, **kwargs):
    if created:
        requisicao = Requisicao.objects.get(aprovacao=instance)
        requisicao.status_requisicao = instance.tipo_aprovacao
        requisicao.save()
        if instance.tipo_aprovacao == 'Aprovada':
             instrumento = Instrumento.objects.get(pk=instance.requisicao.instrumento.id)
             instrumento.stock -= instance.requisicao.quantidade
             instrumento.save()
        # print('Created at:', datetime.now(), instance.tipo_aprovacao)
        # print("Instrumento:", instance.requisicao.instrumento.nome)
        # print("Instrumento:", instrumento.id, instrumento.nome, instance.requisicao.quantidade)
        
post_save.connect(update_requisicao_status, sender=Aprovacao)


# def insert_resumo_via_entrada(sender, instance, created, *args, **kwargs):
#     if created:
#         Resumo.objects.all().delete()
#         resumo_query = Resumo.objects.raw("select 1 AS id, p.nome AS provincia, s.nome AS sector, i.nome AS instrumento, i.stock,"\
#                                   "i.quantidade_necessaria AS necessidade, i.ano, e.id AS entrada_id, e.data_entrada, e.quantidade AS quantidade_entrada, e.fornecedor,"\
#                                   "r.id AS requisicao_id, r.data_requisicao, r.quantidade AS quantidade_requisitada, r.status_requisicao from core_instrumento i" \
#                                   " inner join core_sector s on s.id=i.sector_id" \
#                                   " inner join core_provincia p on i.provincia_id=p.id" \
#                                   " left join core_entrada e on e.instrumento_id=i.id" \
#                                   " left join core_requisicao r on r.instrumento_id=i.id"
#                                    )
#         # provincia = Provincia.objects.get(nome=resumo_query.provincia)
#         # sector = Sector.objects.get(nome=resumo_query.sector)
#         # entrada = Entrada.objects.get(pk=resumo_query.entrada_id)
#         # requisicao = Requisicao.objects.get(pk=resumo_query.requisicao_id)
#         # resumo = Resumo.objects.create(
#         #     provincia=resumo_query.provincia,
#         #     sector=resumo_query.sector,
#         #     instrumento=resumo_query.instrumento,
#         #     entrada_id=resumo_query.entrada_id,
#         #     data_entrada=resumo_query.data_entrada, 
#         #     quantidade=resumo_query.quantidade_entrada,
#         #     fornecedor=resumo_query.fornecedor,
#         #     stock=resumo_query.stock,
#         #     necessidade=resumo_query.necessidade,
#         #     ano=resumo_query.ano,
#         #     id_requisicao= resumo_query.requisicao_id,
#         #     data_requisicao=resumo_query.data_requisicao,
#         #     quantidade_requisicao=resumo_query.quantidade_requisitada,
#         #     status_requisicao=resumo_query.status_requisicao
#         # )
        
#         # resumo.save()
#         print(resumo_query.ano)
# post_save.connect(insert_resumo_via_entrada, sender=Entrada)
        
        
        
    
    
    

app/core/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, View, DetailView
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Avg, Max, Min, Sum

from core.models import Provincia, Sector, Instrumento, Entrada, Requisicao, Aprovacao, Resumo
from core.forms import InstrumentoForm, EntradaForm, SectorForm, RequisicaoForm, AprovacaoForm

class IndexView(ListView):
    template_name = 'index.html'
    context_object_name = 'stock_list'
    model = Instrumento
    paginate_by = 6
    
    
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
       # context['stock_manica'] = Instrumento.objects.filter(provincia=Provincia.objects.get(nome='Manica')).count() #.aggregate(Sum('stock'))['stock__sum']
       # context['stock_sofala'] = Instrumento.objects.filter(provincia=Provincia.objects.get(nome='Sofala')).count() #.aggregate(Sum('stock'))['stock__sum']
       # context['stock_tete']   = Instrumento.objects.filter(provincia=Provincia.objects.get(nome='Tete')).count() #.aggregate(Sum('stock'))['stock__sum']
        # context['stock_niassa'] = Instrumento.objects.filter(provincia=Provincia.objects.get(nome='Niassa')).count() #.aggregate(Sum('stock'))['stock__sum']
        # if context['stock_manica'] is None:
        #    context['stock_manica'] = 0
        # if context['stock_sofala'] is None:
        #     context['stock_sofala'] = 0
        # if context['stock_tete'] is None:
        #     context['stock_tete'] = 0
        # if context['stock_niassa'] is None:
        #     context['stock_niassa'] = 0
        return context
    
    def get_queryset(self):
        return Instrumento.objects.all()
    
   
    
class SectorListView(ListView):
    template_name = 'sector_list.html'
    context_object_name = 'sectores'
    paginate_by = 6
    model = Sector
    
class SectorCreateView(SuccessMessageMixin, CreateView):
    template_name = 'sector_create.html'
    form_class = SectorForm
    success_url = '/'
    success_message = 'Sector adicionado com sucesso'
    
    def form_valid(self, form):
        sector = form.save(commit=False)
        sector.save()
        return redirect(self.success_url)
    
    
class TodosInstrumentosListView(ListView):
    template_name = 'instrumento_list.html'
    paginate_by = 6
    context_object_name = 'instrumentos'
    model = Instrumento
    
      
    
class InstrumentoCreateView(SuccessMessageMixin, CreateView):
    template_name = 'instrumento_create.html'
    form_class = InstrumentoForm
    success_url = '/'
    success_message = 'Instrumento adicionado com sucesso'
    
    def form_valid(self, form):
        instrumento = form.save(commit=False)
        instrumento.save()
        return redirect(self.success_url)
    
   
class EntradasListView(ListView):
    template_name = 'entrada_list.html'
    context_object_name = 'entradas'
    paginate_by = 6
    model = Entrada
    
    def get_queryset(self):
        qs = Entrada.objects.all()
        return qs
    
class EntradaCreateView(SuccessMessageMixin, CreateView):
    template_name = 'entrada_create.html'
    form_class = EntradaForm
    success_url = '/'
    success_message = 'Movimento adicionado com sucesso'
    
    def form_valid(self, form):
        entrada = form.save(commit=False)
        entrada.save()
        return redirect(self.success_url)


def load_instrumentos(request):
    sector_id = request.GET.get('sector')
    instrumentos = Instrumento.objects.filter(sector_id=sector_id).order_by('nome')
    context = {'instrumentos': instrumentos}
    return render(request, 'instrumento_dropdown_list_options.html', context)

class ResumoListView(ListView):
    template_name = 'resumo_instrumentos.html'
    context_object_name = 'resumo_instrumentos'
    paginate_by = 6
    model = Resumo
    
    def get_queryset(self):
        qs = Resumo.objects.raw("select 1 AS id, p.nome AS provincia, s.nome AS sector, i.nome AS instrumento, i.stock,"\
                                  "i.quantidade_necessaria AS necessidade, i.ano, e.id AS entrada_id, e.data_entrada, e.quantidade AS quantidade_entrada, e.fornecedor,"\
                                  "r.id AS requisicao_id, r.data_requisicao, r.quantidade AS quantidade_requisitada, r.status_requisicao from core_instrumento i" \
                                  " inner join core_sector s on s.id=i.sector_id" \
                                  " inner join core_provincia p on i.provincia_id=p.id" \
                                  " left join core_entrada e on e.instrumento_id=i.id" \
                                  " left join core_requisicao r on r.instrumento_id=i.id"
                                   )
        return qs
    
    
       

class RequisicaoListView(ListView):
    template_name = 'requisicao_list.html'
    context_object_name = 'requisicoes'
    paginate_by = 6
    model = Requisicao
    
    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.select_related('provincia')
        qs = qs.select_related('sector')
        qs = qs.select_related('instrumento')
        
        return qs
    
class RequisicaoCreateView(SuccessMessageMixin, CreateView):
    template_name = 'requisicao_create.html'
    form_class = RequisicaoForm
    success_url = '/'
    success_message = 'Requisicao adicionada com sucesso'
    
    def form_valid(self, form):
        requisicao = form.save(commit=False)
        requisicao.save()
        return redirect(self.success_url)
    
    
class RequisicaoUpdateView(UpdateView):
    template_name = 'requisicao_create.html'
    model = Requisicao
    success_url = '/requisicao/'
    fields = '__all__'
    pk_url_kwarg = 'pk'
    
    
    # def form_valid(self, form):
    #     requisicao = form.save(commit=False)
    #     requisicao.save()
    #     return redirect(self.success_url)
    
class RequisicaoDetailView(DetailView):
    model = Requisicao
    context_object_name = 'requisicao'
    template_name = 'requisicao_detail.html'
    pk_url_kwarg = 'pk'
    
class AprovarRequisicao(SuccessMessageMixin, CreateView):
    template_name = 'aprovacao_create.html'
    form_class = AprovacaoForm
    success_url = '/resumo'
    success_message = 'Requisicao adicionada com sucesso'
    
    def form_valid(self, form):
        aprovacao = form.save(commit=False)
        aprovacao.save()
        return redirect(self.success_url)
    
    def get_queryset(self):
        pass
    

def load_requisicoes(request):
    requisicao_id = request.GET.get('requisicao')
    requisicao = Requisicao.objects.filter(pk=requisicao_id).order_by('nome')
    context = {'requisicao': requisicao}
    return render(request, 'requisicao_dropdown_list_options.html', context)
       
    
    

app/core/templates/aprovacao_create.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container">
 <!--/forms-inner-->
<div class="forms-inner">
<!--/set-1-->
<div class="set-1">
  <div class="graph-2 general">
    <h3 class="inner-tittle two">Aprovar Requisicao</h3>
      <div class="grid-1">
          <div class="form-body">
            <form class="form-horizontal" method="post" id="aprovacaoForm" data-requisicao-url="{% url 'core:aprovacao-requisicao' %}">
            {% csrf_token %}
            {% for field in form.visible_fields %}
              <div class="form-group">
              <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {{ field|add_class:"formControl" }}
              {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
              {% endfor %}
              </div>
            {% endfor %}
            <div class="form-group">
              
              <button type="submit" class="btn btn-default">
                <span class="glyphicon glyphicon-ok"></span>Salvar
              </button>
              <a href="{% url 'core:index' %}" class="btn btn-danger">Cancelar</a>
              
            </div>
            
            </form> 
          </div>
        </div> 
      </div>
    </div>
  </div>
</div>

{% comment %} <script>
  $("#id_sector").change(function() {
    var url = $("#entradaForm").attr("data-instrumentos-url");
    var sectorId = $(this).val();

    $.ajax({
      url: url,
      data: {
        'sector': sectorId
      },
      success: function(data) {
        $("#id_instrumento").html(data);
      }
    });
  }); {% endcomment %}

</script>
{% endblock content  %} 

app/core/templates/entrada_list.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
<div class="container">

<h3 class="inner-tittle two">Lista de Movimentos de Entrada de SI</h3>
<div class='row'>
    <a href="{% url 'core:entrada-new'%}" class="btn btn-success float-right">
        <span class="glyphicon glyphicon-plus"></span>Novo
        </a>

</div>

<div class="graph">
<div class="tables">
    <table class="table table-hover">
     <thead>
        <tr>
            <th>Data de Entrada</th>
            <th>Provincia</th>
            <th>Fornecedor</th>
            <th>Sector</th>
            <th>Instrumento</th>
            <th>quantidade</th>
            <th>Feito por</th>
            <th>Feito em</th>
        
        </tr>
     </thead>
     <tbody>
        <tr>
        {% for entrada in entradas  %}
            <td>{{entrada.data_entrada|date:'d-m-Y'}}</td>
            <td>{{entrada.provincia.nome}}</td>
            <td>{{entrada.fornecedor}}</td>
            <td>{{entrada.sector.nome}}</td>
            <td>{{entrada.instrumento.nome}}</td>
            <td>{{entrada.quantidade}}</td>
            <td>{{entrada.feito_por}}</td>
            <td>{{entrada.feito_em|date:'d-m-Y'}}</td>
        </tr>
        {% endfor %}     
        </tbody>
      
    </table> 
   {% include 'layouts/paginations.html' %}
</div>
<a href="#" class="btn btn-success">
<span class="glyphicon glyphicon-sort"></span>Exportar
</a>
</div>

</div>

{% endblock content %}

app/core/templates/necessidade_create.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container">
 <!--/forms-inner-->
<div class="forms-inner">
<!--/set-1-->
<div class="set-1">
  <div class="graph-2 general">
    <h3 class="inner-tittle two">Necessidade</h3>
      <div class="grid-1">
          <div class="form-body">
             <form class="form-horizontal" method="post" id="necessidadeForm" data-instrumentos-url="{% url 'core:listar_instrumentos' %}">
            {% csrf_token %}
            {% for field in form.visible_fields %}
              <div class="form-group">
              <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {{ field|add_class:"formControl" }}
              {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
              {% endfor %}
              </div>
            {% endfor %}
            <div class="form-group">
              
              <button type="submit" class="btn btn-default">
                <span class="glyphicon glyphicon-ok"></span>Salvar
              </button>
              <a href="{% url 'core:index' %}" class="btn btn-danger">Cancelar</a>
              
            </div>
            
            </form> 
          </div>
        </div> 
      </div>
    </div>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
  $("#id_sector").change(function() {
    var url = $("#necessidadeForm").attr("data-instrumentos-url");
    var sectorId = $(this).val();

    $.ajax({
      url: url,
      data: {
        'sector': sectorId
      },
      success: function(data) {
        $("#id_instrumento").html(data);
      }
    });
  });

</script>
{% endblock content  %} 

app/core/templates/requisicao_create.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
 <!--/forms-inner-->
<div class="forms-inner">
<!--/set-1-->
<div class="set-1">
  <div class="graph-2 general">
    <h3 class="inner-tittle two">Registar Requisicao</h3>
      <div class="grid-1">
          <div class="form-body">
            <form class="form-horizontal" method="post" id="requisicaoForm" data-instrumentos-url="{% url 'core:listar_instrumentos' %}">
            {% csrf_token %}
            {% for field in form.visible_fields %}
              <div class="form-group">
              <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {{ field|add_class:"formControl" }}
              {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
              {% endfor %}
              </div>
            {% endfor %}
            <div class="form-group">
              
              <button type="submit" class="btn btn-default">
                <span class="glyphicon glyphicon-ok"></span>Salvar
              </button>
              <a href="{% url 'core:index' %}" class="btn btn-danger">Cancelar</a>
              
            </div>
            
            </form> 
          </div>
        </div> 
      </div>
    </div>
  </div>
</div>
{% comment %} <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> {% endcomment %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
{% comment %} <script>
  $("#id_provincia").change(function() {
    var url = $("#entradaForm").attr("data-sectores-url");
    var provinciaId = $(this).val();

    $.ajax({
      url: url,
      data: {
        'provincia': provinciaId
      },
      success: function(data) {
        $("#id_sector").html(data);
      }
    });
  });
</script> {% endcomment %}
<script>
  $("#id_sector").change(function() {
    var url = $("#requisicaoForm").attr("data-instrumentos-url");
    var sectorId = $(this).val();

    $.ajax({
      url: url,
      data: {
        'sector': sectorId
      },
      success: function(data) {
        $("#id_instrumento").html(data);
      }
    });
  });

</script>


{% endblock content  %} 

app/core/templates/requisicao_edit.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
 <!--/forms-inner-->
<div class="forms-inner">
<!--/set-1-->
<div class="set-1">
  <div class="graph-2 general">
    <h3 class="inner-tittle two">Registar Requisicao</h3>
      <div class="grid-1">
          <div class="form-body">
            <form class="form-horizontal" method="post" id="requisicaoForm" data-instrumentos-url="{% url 'core:listar_instrumentos' %}">
            {% csrf_token %}
            {% for field in form.visible_fields %}
              <div class="form-group">
              <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {{ field|add_class:"formControl" }}
              {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
              {% endfor %}
              </div>
            {% endfor %}
            <div class="form-group">
              
              <button type="submit" class="btn btn-default">
                <span class="glyphicon glyphicon-ok"></span>Salvar
              </button>
              <a href="{% url 'core:index' %}" class="btn btn-danger">Cancelar</a>
              
            </div>
            
            </form> 
          </div>
        </div> 
      </div>
    </div>
  </div>
</div>
{% comment %} <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> {% endcomment %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
{% comment %} <script>
  $("#id_provincia").change(function() {
    var url = $("#entradaForm").attr("data-sectores-url");
    var provinciaId = $(this).val();

    $.ajax({
      url: url,
      data: {
        'provincia': provinciaId
      },
      success: function(data) {
        $("#id_sector").html(data);
      }
    });
  });
</script> {% endcomment %}
<script>
  $("#id_sector").change(function() {
    var url = $("#requisicaoForm").attr("data-instrumentos-url");
    var sectorId = $(this).val();

    $.ajax({
      url: url,
      data: {
        'sector': sectorId
      },
      success: function(data) {
        $("#id_instrumento").html(data);
      }
    });
  });

</script>


{% endblock content  %} 

app/core/templates/requisicao_list.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
<div class="container">

<h3 class="inner-tittle two">Lista de Requisicoes</h3>
<div class='row'>
    <a href="{% url 'core:requisicao-new'%}" class="btn btn-success float-right">
        <span class="glyphicon glyphicon-plus"></span>Novo
        </a>

</div>

<div class="graph">
<div class="tables">
    <table class="table table-hover">
     <thead>
        <tr>
            <th>Data de Requisicao</th>
            <th>Provincia</th>
            <th>Instrumento</th>
            <th>Qtd.</th>
            <th>Stock</th>
            <th>Status</th>
            <th>Accoes</th>
           
        
        </tr>
     </thead>
     <tbody>
        <tr>
        {% for requisicao in requisicoes  %}
            <td>{{requisicao.data_requisicao|date:'d-m-Y'}}</td>
            <td>{{requisicao.provincia.nome}}</td>
            <td>{{requisicao.instrumento.nome}}</td>
            <td>{{requisicao.quantidade}}</td>
            <td>{{requisicao.instrumento.stock}}</td>
            {% if requisicao.status_requisicao == 'Pendente' %}
            <td><span class="label label-warning">{{requisicao.status_requisicao}}</span></td>
            {% elif requisicao.status_requisicao == 'Rejeitada' %}
            <td><span class="label label-danger">{{requisicao.status_requisicao}}</span></td>
            {% elif requisicao.status_requisicao == 'Aprovada' %}
            <td><span class="label label-success">{{requisicao.status_requisicao}}</span></td>
            {% endif %}
            <td>
                <a href="{% url 'core:requisicao-update' pk=requisicao.id %}" class="btn-sm btn-success">
                   Editar
                </a>

            </td>

        </tr>
        {% endfor %}     
        </tbody>
      
    </table> 
   {% include 'layouts/paginations.html' %}
</div>
</div>
<a href="#" class="btn btn-success">
<span class="glyphicon glyphicon-sort"></span>Exportar
</a>
</div>

</div>

{% endblock content %}